### ISSUE TITLE
Wrong Version Syntax in Doc

### ISSUE THREAD

**Issue by maidl** [restackio/update-json-file-action#65]
[Usage](https://github.com/restackio/update-json-file-action?tab=readme-ov-file#usage) states `v2.1` as action version - this can not be resolved (`Error: Unable to resolve action 'restackio/update-json-file-action@v2.1', unable to find version 'v2.1'`).
![image](https://github.com/restackio/update-json-file-action/assets/25984586/a50253a6-cd7c-4a51-812c-cfb85550bb00)

Please remove the 'v' prefix: `restackio/update-json-file-action@2.1`.

**Comment by mohsiniscoding** [comment]
@restackio, please update this.
